#!/bin/bash
#
# /etc/init.d/milter-zipcrypt
#
# chkconfig:   - 79 21
# description: Milter for encryption of attachment files
# processname: milter-zipcrypt
# config:      /etc/sysconfig/milter-zipcrypt
# pidfile:     /var/run/milter-zipcrypt/milter-zipcrypt.pid

# Source function library.
. /etc/init.d/functions

desc="Milter for encryption of attachment files"
name=milter-zipcrypt
prog=${name}
prog_with_path=/usr/sbin/${prog}
user=${name}
pidfile=/var/run/${name}/${name}.pid
config=/etc/sysconfig/${name}.conf

SOCKET=local:/var/run/${name}/${name}.sock
EXTRA_FLAGS=""
[ -r /etc/sysconfig/${name} ] && . /etc/sysconfig/${name}

start() {
	echo -n "Starting ${desc} (${prog}): "
        daemon --user ${user} ${prog_with_path} -c ${config} -p ${pidfile} -s ${SOCKET} ${EXTRA_FLAGS}
        RETVAL=$?
        echo
        if [ ${RETVAL} -eq 0 ]; then
                touch /var/lock/subsys/${name}
                return 0
        else
                return 1
        fi
}

stop() {
	echo -n "Shutting down ${desc}: "
        rm -f /var/lock/subsys/${name}
        killproc ${prog}
        RETVAL=$?
        echo
        if [ ${RETVAL} -eq 0 ]; then
                rm -f ${pidfile}
                return 0
        else
                return 1
        fi
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
        status -p ${pidfile} ${prog}
	;;
    restart|reload)
    	stop
	start
	;;
    condrestart)
	[ -f /var/lock/subsys/${name} ] && stop
        start
	;;
    *)
	echo "Usage: ${name} {start|stop|status|reload|restart}"
	exit 1
	;;
esac
exit $?
